[package]
name = "editor"
version = "0.1.0"
authors = ["Andr√© Twupack <atwupack@mailbox.org>"]
edition = "2018"

[dependencies]
glib = "^0"
gio = "^0"
downcast-rs = "1.0.3"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_16"]
